[template]
src  = "cluster.xml.tmpl"
dest = "/app/conf/cluster.xml"
keys = [
  "/cluster/group/name",
  "/cluster/group/password",
  "/cluster/aws/enabled",
  "/cluster/aws/region",
  "/cluster/aws/iam/role",
  "/cluster/aws/tag/key",
  "/cluster/aws/tag/value",
]